1602489600086
1602576009746
1602662400104
1602668043330
1602748809391
1602835200088
1602921600077
1603008000065
1603094409263
1603180800108
1603267200074
1603353600069
1603440000092
1603526400087
1603612800067
1603699200072
1603785600091
1603872000089
1603958400088
1604044800073
1604047228977
1604047418293
1604056432278
1604131200094
1604217600068
1604304000100
1604390400104
1604476800069
1604563200106
1604649600072
1604736000105
1604822400112
1604908800086
1604995200068
1605081600072
1605168000087
1605254400091
1605340800082
1605427200111
1605513600109
1605600000104
1605686400072
1605772800110
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process

    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 104, in search_and_push

    found2 = match2[0]
IndexError: list index out of range

